In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('heart.csv')

In [49]:
dataset.head(50)

Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0    40    1           ATA        140          289          0           1   
1    49    0           NAP        160          180          0           1   
2    37    1           ATA        130          283          0           2   
3    48    0           ASY        138          214          0           1   
4    54    1           NAP        150          195          0           1   
5    39    1           NAP        120          339          0           1   
6    45    0           ATA        130          237          0           1   
7    54    1           ATA        110          208          0           1   
8    37    1           ASY        140          207          0           1   
9    48    0           ATA        120          284          0           1   
10   37    0           NAP        130          211          0           1   
11   58    1           ATA        136          164          0           2   
12   39    1           ATA        120          204          0           1   
13   49    1           ASY        140          234          0           1   
14   42    0           NAP        115          211          0           2   
15   54    0           ATA        120          273          0           1   
16   38    1           ASY        110          196          0           1   
17   43    0           ATA        120          201          0           1   
18   60    1           ASY        100          248          0           1   
19   36    1           ATA        120          267          0           1   
20   43    0            TA        100          223          0           1   
21   44    1           ATA        120          184          0           1   
22   49    0           ATA        124          201          0           1   
23   44    1           ATA        150          288          0           1   
24   40    1           NAP        130          215          0           1   
25   36    1           NAP        130          209          0           1   
26   53    1           ASY        124          260          0           2   
27   52    1           ATA        120          284          0           1   
28   53    0           ATA        113          468          0           1   
29   51    1           ATA        125          188          0           1   
30   53    1           NAP        145          518          0           1   
31   56    1           NAP        130          167          0           1   
32   54    1           ASY        125          224          0           1   
33   41    1           ASY        130          172          0           2   
34   43    0           ATA        150          186          0           1   
35   32    1           ATA        125          254          0           1   
36   65    1           ASY        140          306          1           1   
37   41    0           ATA        110          250          0           2   
38   48    0           ATA        120          177          1           2   
39   48    0           ASY        150          227          0           1   
40   54    0           ATA        150          230          0           1   
41   54    0           NAP        130          294          0           2   
42   35    1           ATA        150          264          0           1   
43   52    1           NAP        140          259          0           2   
44   43    1           ASY        120          175          0           1   
45   59    1           NAP        130          318          0           1   
46   37    1           ASY        120          223          0           1   
47   50    1           ATA        140          216          0           1   
48   36    1           NAP        112          340          0           1   
49   41    1           ASY        110          289          0           1   

    MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0     172      

In [6]:
dataset.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [7]:
dataset['Sex'].unique()

array(['M', 'F'], dtype=object)

In [8]:
dataset['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Sex'] = le.fit_transform(dataset['Sex'])

In [10]:
print(dataset)

     Age  Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40    1           ATA        140          289          0     Normal   
1     49    0           NAP        160          180          0     Normal   
2     37    1           ATA        130          283          0         ST   
3     48    0           ASY        138          214          0     Normal   
4     54    1           NAP        150          195          0     Normal   
..   ...  ...           ...        ...          ...        ...        ...   
913   45    1            TA        110          264          0     Normal   
914   68    1           ASY        144          193          1     Normal   
915   57    1           ASY        130          131          0     Normal   
916   57    0           ATA        130          236          0        LVH   
917   38    1           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172     

In [11]:
dataset['RestingECG'] = le.fit_transform(dataset['RestingECG'])

In [12]:
dataset['ExerciseAngina'] = le.fit_transform(dataset['ExerciseAngina'])

In [13]:
dataset['ST_Slope'] = le.fit_transform(dataset['ST_Slope'])

In [14]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
print(X)

[[40 1 'ATA' ... 0 0.0 2]
 [49 0 'NAP' ... 0 1.0 1]
 [37 1 'ATA' ... 0 0.0 2]
 ...
 [57 1 'ASY' ... 1 1.2 1]
 [57 0 'ATA' ... 0 0.0 1]
 [38 1 'NAP' ... 0 0.0 2]]


In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[60 17]
 [11 96]]


0.8478260869565217

In [21]:
print(y_test, y_pred)

[1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1
 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0
 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 0 0 1 1
 1 1 1 1 0 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 0 1 1 1 0 1] [1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 0 1
 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1
 1 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1
 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 1 0 1 1 0 0 1]


In [22]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.8478260869565217

In [23]:
#support vector
from sklearn.model_selection import train_test_split
X_trains, X_tests, y_trains, y_tests = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trains = sc.fit_transform(X_trains)
X_tests = sc.transform(X_tests)

In [25]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_trains, y_trains)

SVC(kernel='linear', random_state=0)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_preds = classifier.predict(X_tests)
cm = confusion_matrix(y_tests, y_preds)
print(cm)
accuracy_score(y_tests, y_preds)

[[56 21]
 [11 96]]


0.8260869565217391

In [27]:
#random forest

from sklearn.model_selection import train_test_split
X_trainr, X_testr, y_trainr, y_testr = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trainr = sc.fit_transform(X_trainr)
X_testr = sc.transform(X_testr)

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_trainr, y_trainr)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predr = classifier.predict(X_test)
cm = confusion_matrix(y_testr, y_predr)
print(cm)
accuracy_score(y_testr, y_predr)

[[64 13]
 [14 93]]


0.8532608695652174

In [31]:
#naive bayes

from sklearn.model_selection import train_test_split
X_trainn, X_testn, y_trainn, y_testn = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trainn = sc.fit_transform(X_trainn)
X_testn = sc.transform(X_testn)

In [33]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_trainn, y_trainn)

GaussianNB()

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predn = classifier.predict(X_testn)
cm = confusion_matrix(y_testn, y_predn)
print(cm)
accuracy_score(y_testn, y_predn)

[[ 68  24]
 [ 15 123]]


0.8304347826086956

In [35]:
#logistic regression
from sklearn.model_selection import train_test_split
X_trainl, X_testl, y_trainl, y_testl = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trainl = sc.fit_transform(X_trainl)
X_testl = sc.transform(X_testl)

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_trainl, y_trainl)

LogisticRegression(random_state=0)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predl = classifier.predict(X_testl)
cm = confusion_matrix(y_testl, y_predl)
print(cm)
accuracy_score(y_testl, y_predl)

[[ 67  25]
 [ 16 122]]


0.8217391304347826

In [39]:
#kernal svm
from sklearn.model_selection import train_test_split
X_traink, X_testk, y_traink, y_testk = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_traink = sc.fit_transform(X_traink)
X_testk = sc.transform(X_testk)

In [41]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_traink, y_traink)

SVC(random_state=0)

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predk = classifier.predict(X_testk)
cm = confusion_matrix(y_testk, y_predk)
print(cm)
accuracy_score(y_testk, y_predk)

[[ 69  23]
 [ 12 126]]


0.8478260869565217

In [43]:
#decision_tree_classification

from sklearn.model_selection import train_test_split
X_traind, X_testd, y_traind, y_testd = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_traind = sc.fit_transform(X_traind)
X_testd = sc.transform(X_testd)

In [45]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_traind, y_traind)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predd = classifier.predict(X_testd)
cm = confusion_matrix(y_testd, y_predd)
print(cm)
accuracy_score(y_testd, y_predd)

[[ 72  20]
 [ 16 122]]


0.8434782608695652